<?php
/**
 * Leases → Views/documents/notice_to_quit.php
 * Formal Common Law notice to quit served on the tenant.
 */
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Notice to Quit — <?= e($lease['code']) ?></title>
<style>
  body { font-family: Georgia, 'Times New Roman', serif; margin: 3em auto; max-width: 44em; color: #111; line-height: 1.6; }
  h1 { font-size: 1.25em; text-transform: uppercase; letter-spacing: .1em; text-align: center; }
  .ref { text-align: right; color: #333; }
  .to { border: 1px solid #999; padding: .8em 1em; margin: 1.5em 0; }
  .sig { border-top: 1px solid #111; margin-top: 3em; padding-top: .5em; width: 40%; }
  .em { font-weight: bold; }
  .footer { margin-top: 2em; font-size: .88em; color: #444; border-top: 1px dashed #999; padding-top: 1em; }
</style>
</head>
<body>

<p class="ref">Ref: <?= e($lease['code']) ?> / NTQ<br>Date: <?= e(date('jS F Y', strtotime($notice['issue_date']))) ?></p>

<h1>Notice to Quit</h1>

<div class="to">
  To: <strong><?= e($lease['tenant_name']) ?></strong><br>
  <?= $lease['tenant_phone'] ? 'Tel: ' . e($lease['tenant_phone']) . '<br>' : '' ?>
  Premises: <strong>Unit <?= e($lease['unit_code']) ?>, <?= e($lease['building_name']) ?>, <?= e($lease['quarter']) ?>, <?= e($lease['city']) ?></strong>
</div>

<p>WHEREAS you hold the above-named premises from the Lessor under a tenancy agreement dated
<?= e(date('jS F Y', strtotime($lease['start_date']))) ?> (reference <?= e($lease['code']) ?>)
at a rent of <?= e(fmt_xaf($lease['rent_xaf'])) ?> per <?= e($lease['billing_cycle']) ?>;</p>

<p>AND WHEREAS the ground for this notice is: <span class="em"><?= e($notice['reason']) ?></span>;</p>

<p>TAKE NOTICE that, pursuant to the terms of the said agreement and the
<?= e($lease['legal_system'] === 'common_law' ? 'Common Law' : 'applicable law') ?> applicable in
<?= e($lease['jurisdiction']) ?>, the Lessor requires you to <span class="em">quit and deliver up
possession of the said premises on or before <?= e(date('l, jS F Y', strtotime($notice['expiry_date']))) ?></span>,
being the expiry of <?= (int) $notice['days'] ?> days from the date of service of this notice.</p>

<p>TAKE FURTHER NOTICE that should you fail to quit and deliver up possession as required, the
Lessor shall institute proceedings for the recovery of premises and accrued rent before the
competent court in <?= e($lease['jurisdiction']) ?>, and shall seek costs, without further
reference to you. The Lessor shall not resort to self-help eviction.</p>

<p>Payment of all rent and charges outstanding as at the date hereof, if made before expiry of
this notice, may be considered toward remedying the breach at the Lessor’s discretion.</p>

<div class="sig">
  For the Lessor:<br>
  LittleDrops Property Management<br><br>
  Signature: ______________________
</div>

<div class="footer">
  Served by: <?= e(current_user()['full_name'] ?? 'PBMS') ?> ·
  Generated by <?= e(t('app.name')) ?> on <?= e(date('d M Y H:i')) ?>.
  This notice is a system-generated draft based on Common Law practice in the Anglophone
  Regions of Cameroon; service and form must be confirmed with counsel (personal service,
  registered post or service by bailiff as the case may require).
</div>

</body>
</html>
